package by.test.task.core.exceptions.abstracts;

@FunctionalInterface
public interface RunnableThrows {
    void run() throws Exception;
}